### ISSUE TITLE
Kartenladen-Button neben Lokalisierungs-Button

### ISSUE THREAD

**Issue by hagenstrahl** [immergutrocken/website#128]
- [x] Kartenladen C2A Button neben Lokalisierungs-Button
- [x] auf Englisch "Ticket Shop"
- [x] Abstand Desktop: 16px
- [x] Abstand Mobile: 8px
- [x] Hintergrundfarbe des Buttons: #98CE58

**Comment by hagenstrahl** [comment]
@immergutrocken/website-team 
Hallo zusammen,
soll der Knopf erstmal zu unsere Seite führen (https://immergutrocken.de/article/kartenladen) oder direkt zu Ticket Toaster?

Viele Grüße
Hagen

**Comment by osmodia23** [comment]
Hallo @hagenstrahl,

danke für den Button! Gerade linkt er noch auf die Kartenladen Seite, kann der bitte direkt zu Ticket Toaster leiten? Vielen lieben Dank und Sorry für die späte Antwort!

**Comment by hagenstrahl** [comment]
@steffirogoll Du hast den PR approved. Das heißt, dass Du die Verlinkung zur internen Page besser findest?
Dann würde Dein Favorit gegen dem von @osmodia23 stehen und ich weiß immer noch nicht weiter.
Die Verlinkung zu ändern ist kein Hit.

Ich persönlich finde es auch besser, erstmal zu unserer Page weiterzuleiten, weil da noch n Haufen anderer Infos stehen. Aber wenn es darum geht, schnell eine Conversion zu erzielen, dann ist die Variante direkt zum Ticket Toaster auch sehr gut --> ermöglicht schnelleren Kauf.

**Comment by steffirogoll** [comment]
@hagenstrahl oh wow echt, hab ich? Uppsi. Ja dann lass mal direkt zu Tickettoaster verlinken, wenn wir merken, dass sich dann die Nachfragen beim Büroteam häufen, dann müssen wir das nochmal ändern.
