### ISSUE TITLE
VÖ Vorbereitung

### ISSUE THREAD

**Issue by hagenstrahl** [immergutrocken/website#187]
- [x] News Leiste wieder einfügen (wie gehabt)
- [x] Bands auf der Landing Page
- [x] ~~Platzhalter: "Wir kommen in die Puschen: am 26. Januar gibt's die ersten Künstler*innen und Neuigkeiten für das Immergut Festival 2022."~~
- [x] Künstler unpublishen @steffirogoll 
- [x] neuer Banner (wird nachgereicht von @osmodia23)

**Comment by steffirogoll** [comment]
![01_immergut_website_portraitformat4](https://user-images.githubusercontent.com/60503213/150766875-727081c5-c1c1-4551-8402-74c850ddcbc3.png)
![01_immergut_website_portraitformat5](https://user-images.githubusercontent.com/60503213/150766892-d2b87aca-e263-4792-9067-4bc664fbce2c.png)
